# Generated by Django 5.0.6 on 2024-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisuals', '0008_alter_data_insight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
