# Generated by Django 5.0.6 on 2024-07-01 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataVisuals', '0009_alter_data_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='url',
            field=models.CharField(max_length=555),
        ),
    ]
